apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: zarf-playground
  namespace: zarf-playground
spec:
  url: https://github.com/UncleGedd/zarf-playground
  ref:
    branch: 0.0.1
  interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  url: https://github.com/stefanprodan/podinfo
  ref:
    tag: 6.2.3
  interval: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-install
  namespace: zarf-playground
spec:
  interval: 1m0s
  path: "./upgrade-testing/podinfo"
  sourceRef:
    kind: GitRepository
    name: zarf-playground
    namespace: zarf-playground
  prune: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  targetNamespace: podinfo
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: podinfo
  interval: 1m0s
  values:
    replicaCount: 1
    ui:
      color: "#34577c"
      message: "Hello world"