apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: zarf-playground
  namespace: zarf-playground
spec:
  url: https://github.com/UncleGedd/zarf-playground
  ref:
    branch: main
  interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  url: https://github.com/stefanprodan/podinfo
  ref:
    tag: 6.2.3
  interval: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: zarf-playground
spec:
  interval: 1m0s
  path: "./"
  sourceRef:
    kind: GitRepository
    name: zarf-playground
    namespace: zarf-playground
  prune: true